destination: production
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  toc_levels: "2,3"
highlighter: rouge

paginate: 10
sass:
  sass_dir: _sass
gems: [jekyll-paginate]

version: "master"

doc_versions:
  - master
  - 0.19.2
  - 0.19.1
  - 0.18.1
  - 0.17.2
  - 0.17.1

main_site_url: https://www.bazel.build
docs_site_url: "/"
blog_site_url: https://blog.bazel.build
